
import { LanguageCode } from './types';

export const APP_NAME = "AgriVision AI";

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    welcome: "Welcome to AgriVision",
    selectLang: "Select Language",
    loginTitle: "Farmer Login",
    registerTitle: "Farmer Registration",
    phonePlaceholder: "Mobile Number",
    namePlaceholder: "Full Name",
    start: "Get Started",
    sendOtp: "Send OTP",
    verifyOtp: "Verify & Login",
    resend: "Resend OTP",
    otpPlaceholder: "Enter 4-digit OTP",
    switchLogin: "Already registered? Login",
    switchRegister: "New User? Register",
    errorNameShort: "Name must be more than 6 characters.",
    errorPhoneInvalid: "Please enter a valid 10-digit number.",
    errorUserExists: "Number already registered. Please Login.",
    errorUserNotFound: "Number not found. Please Register first.",
    errorOtpInvalid: "Invalid OTP. Please try again.",
    otpSent: "OTP Sent!",
    home: "Home",
    detect: "Detect Disease",
    profit: "Profit Calc",
    history: "History",
    advisory: "Advisory",
    uploadPhoto: "Upload or Take Photo",
    analyzing: "Analyzing Crop Health...",
    results: "Analysis Results",
    treatment: "Treatment & Solutions",
    organic: "Organic Method",
    chemical: "Chemical Method",
    prevention: "Prevention",
    severity: "Severity",
    confidence: "AI Confidence",
    save: "Save",
    calculate: "Calculate Profit",
    investment: "Total Investment",
    revenue: "Exp. Revenue",
    netProfit: "Net Profit",
    profitPerAcre: "Profit / Acre",
    inputs: "Farming Inputs",
    calculating: "Calculating...",
    weatherTips: "Weather & Tips",
    noHistory: "No previous scans found.",
    weather: "Weather Report",
    temperature: "Temperature",
    humidity: "Humidity",
    wind: "Wind",
    clear: "Clear Sky",
    cloudy: "Cloudy",
    rain: "Rainy",
    fog: "Foggy",
    storm: "Thunderstorm",
    drizzle: "Drizzle",
    locating: "Locating...",
    unknownLoc: "Unknown Location",
    healthyTitle: "Great news! Your plant looks healthy.",
    careTips: "General Care Tips",
    settings: "Settings",
    camera: "Take Photo",
    gallery: "Gallery",
    changeLang: "Change Language",
    updateProfile: "Update Profile"
  },
  hi: {
    welcome: "एग्रीविज़न में आपका स्वागत है",
    selectLang: "भाषा चुनें",
    loginTitle: "किसान लॉगिन",
    registerTitle: "किसान पंजीकरण",
    phonePlaceholder: "मोबाइल नंबर",
    namePlaceholder: "पूरा नाम",
    start: "शुरू करें",
    sendOtp: "ओटीपी भेजें",
    verifyOtp: "सत्यापित करें और लॉगिन करें",
    resend: "ओटीपी पुनः भेजें",
    otpPlaceholder: "4-अंकीय ओटीपी दर्ज करें",
    switchLogin: "पहले से पंजीकृत हैं? लॉगिन करें",
    switchRegister: "नया उपयोगकर्ता? पंजीकरण करें",
    errorNameShort: "नाम 6 अक्षरों से अधिक होना चाहिए।",
    errorPhoneInvalid: "कृपया मान्य 10-अंकीय नंबर दर्ज करें।",
    errorUserExists: "नंबर पहले से पंजीकृत है। कृपया लॉगिन करें।",
    errorUserNotFound: "नंबर नहीं मिला। कृपया पहले पंजीकरण करें।",
    errorOtpInvalid: "अमान्य ओटीपी। कृपया पुन: प्रयास करें।",
    otpSent: "ओटीपी भेजा गया!",
    home: "होम",
    detect: "रोग पहचानें",
    profit: "लाभ कैलकुलेटर",
    history: "इतिहास",
    advisory: "सलाह",
    uploadPhoto: "फोटो अपलोड करें या लें",
    analyzing: "फसल स्वास्थ्य का विश्लेषण...",
    results: "विश्लेषण परिणाम",
    treatment: "उपचार और समाधान",
    organic: "जैविक तरीका",
    chemical: "रासायनिक तरीका",
    prevention: "रोकथाम",
    severity: "गंभीरता",
    confidence: "एआई विश्वास",
    save: "सहेजें",
    calculate: "लाभ की गणना करें",
    investment: "कुल निवेश",
    revenue: "अपेक्षित राजस्व",
    netProfit: "शुद्ध लाभ",
    profitPerAcre: "लाभ / एकड़",
    inputs: "खेती की लागत",
    calculating: "गणना हो रही है...",
    weatherTips: "मौसम और सुझाव",
    noHistory: "कोई पुराना स्कैन नहीं मिला।",
    weather: "मौसम की रिपोर्ट",
    temperature: "तापमान",
    humidity: "नमी",
    wind: "हवा",
    clear: "साफ आसमान",
    cloudy: "बादल छाए रहेंगे",
    rain: "बरसात",
    fog: "कोहरा",
    storm: "आंधी-तूफान",
    drizzle: "बूंदा बांदी",
    locating: "स्थान खोज रहा है...",
    unknownLoc: "अज्ञात स्थान",
    healthyTitle: "खुशखबरी! आपका पौधा स्वस्थ है।",
    careTips: "देखभाल के सुझाव",
    settings: "सेटिंग्स",
    camera: "फोटो लें",
    gallery: "गैलरी",
    changeLang: "भाषा बदलें",
    updateProfile: "प्रोफ़ाइल अपडेट करें"
  },
  te: {
    welcome: "అగ్రివిజన్‌కు స్వాగతం",
    selectLang: "భాషను ఎంచుకోండి",
    loginTitle: "రైతు లాగిన్",
    registerTitle: "రైతు నమోదు",
    phonePlaceholder: "మొబైల్ నంబర్",
    namePlaceholder: "పూర్తి పేరు",
    start: "ప్రారంభించండి",
    sendOtp: "OTP పంపండి",
    verifyOtp: "ధృవీకరించండి & లాగిన్",
    resend: "OTP మళ్ళీ పంపండి",
    otpPlaceholder: "4-అంకెల OTP నమోదు చేయండి",
    switchLogin: "ఇప్పటికే నమోదు చేసుకున్నారా? లాగిన్",
    switchRegister: "కొత్త వినియోగదారు? నమోదు",
    errorNameShort: "పేరు 6 అక్షరాల కంటే ఎక్కువగా ఉండాలి.",
    errorPhoneInvalid: "దయచేసి సరైన 10-అంకెల సంఖ్యను నమోదు చేయండి.",
    errorUserExists: "సంఖ్య ఇప్పటికే నమోదు చేయబడింది. దయచేసి లాగిన్ చేయండి.",
    errorUserNotFound: "సంఖ్య కనుగొనబడలేదు. దయచేసి ముందుగా నమోదు చేసుకోండి.",
    errorOtpInvalid: "చెల్లని OTP. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    otpSent: "OTP పంపబడింది!",
    home: "హోమ్",
    detect: "తెగులు గుర్తింపు",
    profit: "లాభం లెక్క",
    history: "చరిత్ర",
    advisory: "సలహా",
    uploadPhoto: "ఫోటో అప్‌లోడ్ చేయండి",
    analyzing: "పంట ఆరోగ్యాన్ని విశ్లేషిస్తోంది...",
    results: "విశ్లేషణ ఫలితాలు",
    treatment: "చికిత్స & పరిష్కారాలు",
    organic: "సేంద్రీయ పద్ధతి",
    chemical: "రసాయన పద్ధతి",
    prevention: "నివారణ",
    severity: "తీవ్రత",
    confidence: "AI నమ్మకం",
    save: "సేవ్ చేయండి",
    calculate: "లాభాన్ని లెక్కించండి",
    investment: "మొత్తం పెట్టుబడి",
    revenue: "ఆశించిన ఆదాయం",
    netProfit: "నికర లాభం",
    profitPerAcre: "లాభం / ఎకరా",
    inputs: "వ్యవసాయ ఖర్చులు",
    calculating: "లెక్కిస్తోంది...",
    weatherTips: "వాతావరణం & చిట్కాలు",
    noHistory: "పాత స్కాన్‌లు ఏవీ కనుగొనబడలేదు.",
    weather: "వాతావరణ నివేదిక",
    temperature: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    wind: "గాలి",
    clear: "నిర్మలమైన ఆకాశం",
    cloudy: "మేఘావృతం",
    rain: "వర్షం",
    fog: "పొగమంచు",
    storm: "ఉరుములతో కూడిన వర్షం",
    drizzle: "తుంపరలు",
    locating: "స్థానాన్ని గుర్తిస్తోంది...",
    unknownLoc: "తెలియని ప్రదేశం",
    healthyTitle: "శుభవార్త! మీ మొక్క ఆరోగ్యంగా ఉంది.",
    careTips: "సంరక్షణ చిట్కాలు",
    settings: "సెట్టింగులు",
    camera: "ఫోటో తీయండి",
    gallery: "గ్యాలరీ",
    changeLang: "భాష మార్చండి",
    updateProfile: "ప్రొఫైల్ నవీకరించండి"
  },
  ta: {
    welcome: "அக்ரிவிஷனுக்கு வரவேற்கிறோம்",
    selectLang: "மொழியைத் தேர்ந்தெடுக்கவும்",
    loginTitle: "விவசாயி உள்நுழைவு",
    registerTitle: "விவசாயி பதிவு",
    phonePlaceholder: "மொபைல் எண்",
    namePlaceholder: "முழு பெயர்",
    start: "தொடங்கவும்",
    sendOtp: "OTP அனுப்பு",
    verifyOtp: "சரிபார்த்து உள்நுழையவும்",
    resend: "OTP மீண்டும் அனுப்பு",
    otpPlaceholder: "4-இலக்க OTP உள்ளிடவும்",
    switchLogin: "ஏற்கனவே பதிவு செய்துள்ளீர்களா? உள்நுழை",
    switchRegister: "புதிய பயனர்? பதிவு செய்யவும்",
    errorNameShort: "பெயர் 6 எழுத்துக்களுக்கு மேல் இருக்க வேண்டும்.",
    errorPhoneInvalid: "சரியான 10 இலக்க எண்ணை உள்ளிடவும்.",
    errorUserExists: "எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. உள்நுழையவும்.",
    errorUserNotFound: "எண் காணப்படவில்லை. முதலில் பதிவு செய்யவும்.",
    errorOtpInvalid: "தவறான OTP. மீண்டும் முயற்சிக்கவும்.",
    otpSent: "OTP அனுப்பப்பட்டது!",
    home: "முகப்பு",
    detect: "நோய் கண்டறி",
    profit: "லாபம் கணிப்பான்",
    history: "வரலாறு",
    advisory: "ஆலோசனை",
    uploadPhoto: "புகைப்படம் பதிவேற்றவும்",
    analyzing: "பயிர் ஆரோக்கியத்தை ஆய்வு செய்கிறது...",
    results: "ஆய்வு முடிவுகள்",
    treatment: "சிகிச்சை & தீர்வுகள்",
    organic: "இயற்கை முறை",
    chemical: "ரசாயன முறை",
    prevention: "தடுப்பு முறைகள்",
    severity: "தீவிரம்",
    confidence: "AI நம்பிக்கை",
    save: "சேமி",
    calculate: "லாபத்தைக் கணக்கிடு",
    investment: "மொத்த முதலீடு",
    revenue: "எதிர்பார்க்கப்படும் வருவாய்",
    netProfit: "நிகர லாபம்",
    profitPerAcre: "லாபம் / ஏக்கர்",
    inputs: "விவசாய இடுபொருட்கள்",
    calculating: "கணக்கிடுகிறது...",
    weatherTips: "வானிலை & குறிப்புகள்",
    noHistory: "முந்தைய பதிவுகள் எதுவும் இல்லை.",
    weather: "வானிலை அறிக்கை",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    wind: "காற்று",
    clear: "தெளிவான வானம்",
    cloudy: "மேகமூட்டம்",
    rain: "மழை",
    fog: "மூடுபனி",
    storm: "இடியுடன் கூடிய மழை",
    drizzle: "தூறல்",
    locating: "இடத்தைக் கண்டறிகிறது...",
    unknownLoc: "தெரியாத இடம்",
    healthyTitle: "நற்செய்தி! உங்கள் செடி ஆரோக்கியமாக உள்ளது.",
    careTips: "பராமரிப்பு குறிப்புகள்",
    settings: "அமைப்புகள்",
    camera: "புகைப்படம் எடு",
    gallery: "கேலரி",
    changeLang: "மொழியை மாற்றவும்",
    updateProfile: "சுயவிவரத்தைப் புதுப்பிக்கவும்"
  },
  kn: {
    welcome: "ಅಗ್ರಿವಿಷನ್‌ಗೆ ಸ್ವಾಗತ",
    selectLang: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    loginTitle: "ರೈತ ಲಾಗಿನ್",
    registerTitle: "ರೈತ ನೋಂದಣಿ",
    phonePlaceholder: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    namePlaceholder: "ಪೂರ್ಣ ಹೆಸರು",
    start: "ಪ್ರಾರಂಭಿಸಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ",
    resend: "OTP ಮರುಕಳುಹಿಸಿ",
    otpPlaceholder: "4-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
    switchLogin: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    switchRegister: "ಹೊಸ ಬಳಕೆದಾರ? ನೋಂದಾಯಿಸಿ",
    errorNameShort: "ಹೆಸರು 6 ಅಕ್ಷರಗಳಿಗಿಂತ ಹೆಚ್ಚಿರಬೇಕು.",
    errorPhoneInvalid: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10-ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    errorUserExists: "ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.",
    errorUserNotFound: "ಸಂಖ್ಯೆ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ನೋಂದಾಯಿಸಿ.",
    errorOtpInvalid: "ಅಮಾನ್ಯ OTP. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    otpSent: "OTP ಕಳುಹಿಸಲಾಗಿದೆ!",
    home: "ಮುಖಪುಟ",
    detect: "ರೋಗ ಪತ್ತೆ",
    profit: "ಲಾಭ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    history: "ಇತಿಹಾಸ",
    advisory: "ಸಲಹೆ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyzing: "ಬೆಳೆಯ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ...",
    results: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು",
    treatment: "ಚಿಕಿತ್ಸೆ ಮತ್ತು ಪರಿಹಾರಗಳು",
    organic: "ಸಾವಯವ ವಿಧಾನ",
    chemical: "ರಾಸಾಯನಿಕ ವಿಧಾನ",
    prevention: "ತಡೆಗಟ್ಟುವಿಕೆ",
    severity: "ತೀವ್ರತೆ",
    confidence: "AI ನಂಬಿಕೆ",
    save: "ಉಳಿಸಿ",
    calculate: "ಲಾಭವನ್ನು ಲೆಕ್ಕಹಾಕಿ",
    investment: "ಒಟ್ಟು ಹೂಡಿಕೆ",
    revenue: "ನಿರೀಕ್ಷಿತ ಆದಾಯ",
    netProfit: "ನಿವ್ವಳ ಲಾಭ",
    profitPerAcre: "ಲಾಭ / ಎಕರೆ",
    inputs: "ಕೃಷಿ ವೆಚ್ಚಗಳು",
    calculating: "ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...",
    weatherTips: "ಹವಾಮಾನ ಮತ್ತು ಸಲಹೆಗಳು",
    noHistory: "ಯಾವುದೇ ಹಳೆಯ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ.",
    weather: "ಹವಾಮಾನ ವರದಿ",
    temperature: "ತಾಪಮಾನ",
    humidity: "ತೇವಾಂಶ",
    wind: "ಗಾಳಿ",
    clear: "ಶುಭ್ರ ಆಕಾಶ",
    cloudy: "ಮೋಡ ಕವಿದಿದೆ",
    rain: "ಮಳೆ",
    fog: "ಮಂಜು",
    storm: "ಗುಡುಗು ಸಹಿತ ಮಳೆ",
    drizzle: "ತುಂತುರು ಮಳೆ",
    locating: "ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...",
    unknownLoc: "ಅಜ್ಞಾತ ಸ್ಥಳ",
    healthyTitle: "ಶುಭ ಸುದ್ದಿ! ನಿಮ್ಮ ಗಿಡ ಆರೋಗ್ಯಕರವಾಗಿದೆ.",
    careTips: "ಆರೈಕೆ ಸಲಹೆಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    camera: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    gallery: "ಗ್ಯಾಲರಿ",
    changeLang: "ಭಾಷೆ ಬದಲಿಸಿ",
    updateProfile: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ"
  },
  ml: {
    welcome: "അഗ്രിവിഷനിലേക്ക് സ്വാഗതം",
    selectLang: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    loginTitle: "കർഷക ലോഗിൻ",
    registerTitle: "കർഷക രജിസ്ട്രേഷൻ",
    phonePlaceholder: "മൊബൈൽ നമ്പർ",
    namePlaceholder: "പൂർണ്ണ നാമം",
    start: "തുടങ്ങാം",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക",
    resend: "OTP വീണ്ടും അയയ്ക്കുക",
    otpPlaceholder: "4-അക്ക OTP നൽകുക",
    switchLogin: "ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ടോ? ലോഗിൻ",
    switchRegister: "പുതിയ ഉപയോക്താവ്? രജിസ്റ്റർ ചെയ്യുക",
    errorNameShort: "പേര് 6 അക്ഷരങ്ങളിൽ കൂടുതലായിരിക്കണം.",
    errorPhoneInvalid: "ദയവായി സാധുവായ 10-അക്ക നമ്പർ നൽകുക.",
    errorUserExists: "നമ്പർ ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്. ദയവായി ലോഗിൻ ചെയ്യുക.",
    errorUserNotFound: "നമ്പർ കണ്ടെത്തിയില്ല. ദയവായി ആദ്യം രജിസ്റ്റർ ചെയ്യുക.",
    errorOtpInvalid: "തെറ്റായ OTP. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    otpSent: "OTP അയച്ചു!",
    home: "ഹോം",
    detect: "രോഗം കണ്ടെത്തുക",
    profit: "ലാഭ കണക്കുകൂട്ടൽ",
    history: "ചരിത്രം",
    advisory: "ഉപദേശം",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    analyzing: "വിള ആരോഗ്യം പരിശോധിക്കുന്നു...",
    results: "പരിശോധനാ ഫലങ്ങൾ",
    treatment: "ചികിത്സയും പരിഹാരങ്ങളും",
    organic: "ജൈവ രീതി",
    chemical: "രാസ രീതി",
    prevention: "പ്രതിരോധ മാർഗ്ഗങ്ങൾ",
    severity: "തീവ്രത",
    confidence: "AI വിശ്വാസ്യത",
    save: "സേവ് ചെയ്യുക",
    calculate: "ലാഭം കണക്കാക്കുക",
    investment: "ആകെ നിക്ഷേപം",
    revenue: "പ്രതീക്ഷിക്കുന്ന വരുമാനം",
    netProfit: "അറ്റാദായം",
    profitPerAcre: "ലാഭം / ഏക്കർ",
    inputs: "കാർഷിക ചെലവുകൾ",
    calculating: "കണക്കാക്കുന്നു...",
    weatherTips: "കാലാവസ്ഥയും നിർദ്ദേശങ്ങളും",
    noHistory: "മുൻകാല രേഖകളൊന്നും കണ്ടെത്തിയില്ല.",
    weather: "കാലാവസ്ഥ റിപ്പോർട്ട്",
    temperature: "താപനില",
    humidity: "ഈർപ്പം",
    wind: "കാറ്റ്",
    clear: "തെളിഞ്ഞ ആകാശം",
    cloudy: "മേഘാവൃതം",
    rain: "മഴ",
    fog: "മൂടൽമഞ്ഞ്",
    storm: "ഇടിമിന്നലോട് കൂടിയ മഴ",
    drizzle: "ചാറ്റൽ മഴ",
    locating: "സ്ഥലം കണ്ടെത്തുന്നു...",
    unknownLoc: "അജ്ഞാത സ്ഥലം",
    healthyTitle: "നല്ല വാർത്ത! നിങ്ങളുടെ ചെടി ആരോഗ്യത്തോടെയിരിക്കുന്നു.",
    careTips: "പരിപാലന നിർദ്ദേശങ്ങൾ",
    settings: "ക്രമീകരണങ്ങൾ",
    camera: "ഫോട്ടോ എടുക്കുക",
    gallery: "ഗാലറി",
    changeLang: "ഭാഷ മാറ്റുക",
    updateProfile: "പ്രൊഫൈൽ അപ്‌ഡേറ്റ് ചെയ്യുക"
  },
  mr: {
    welcome: "ऍग्रीव्हिजन मध्ये आपले स्वागत आहे",
    selectLang: "भाषा निवडा",
    loginTitle: "शेतकरी लॉगिन",
    registerTitle: "शेतकरी नोंदणी",
    phonePlaceholder: "मोबाईल नंबर",
    namePlaceholder: "पूर्ण नाव",
    start: "सुरू करा",
    sendOtp: "OTP पाठवा",
    verifyOtp: "पडताळणी करा आणि लॉगिन करा",
    resend: "OTP पुन्हा पाठवा",
    otpPlaceholder: "4-अंकी OTP टाका",
    switchLogin: "आधीच नोंदणीकृत आहात? लॉगिन करा",
    switchRegister: "नवीन वापरकर्ता? नोंदणी करा",
    errorNameShort: "नाव 6 अक्षरांपेक्षा जास्त असावे.",
    errorPhoneInvalid: "कृपया वैध 10-अंकी नंबर टाका.",
    errorUserExists: "नंबर आधीच नोंदणीकृत आहे. कृपया लॉगिन करा.",
    errorUserNotFound: "नंबर सापडला नाही. कृपया आधी नोंदणी करा.",
    errorOtpInvalid: "अवैध OTP. कृपया पुन्हा प्रयत्न करा.",
    otpSent: "OTP पाठवला!",
    home: "होम",
    detect: "रोग ओळखा",
    profit: "नफा कॅल्क्युलेटर",
    history: "इतिहास",
    advisory: "सल्ला",
    uploadPhoto: "फोटो अपलोड करा",
    analyzing: "पिकाचे आरोग्य तपासत आहे...",
    results: "तपासणी निकाल",
    treatment: "उपचार आणि उपाय",
    organic: "सेंद्रिय पद्धत",
    chemical: "रासायनिक पद्धत",
    prevention: "प्रतिबंध",
    severity: "तीव्रता",
    confidence: "AI विश्वास",
    save: "सेव्ह करा",
    calculate: "नफा मोजा",
    investment: "एकूण गुंतवणूक",
    revenue: "अपेक्षित महसूल",
    netProfit: "निव्वळ नफा",
    profitPerAcre: "नफा / एकर",
    inputs: "शेती खर्च",
    calculating: "मोजत आहे...",
    weatherTips: "हवामान आणि टिप्स",
    noHistory: "कोहीही जुने रेकॉर्ड आढळले नाहीत.",
    weather: "हवामान अहवाल",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    wind: "वारा",
    clear: "निरभ्र आकाश",
    cloudy: "ढगाळ",
    rain: "पाऊस",
    fog: "धुके",
    storm: "वादळी पाऊस",
    drizzle: "रिमझिम पाऊस",
    locating: "स्थान शोधत आहे...",
    unknownLoc: "अज्ञात स्थान",
    healthyTitle: "आनंदाची बातमी! तुमचे पीक निरोगी आहे.",
    careTips: "काळजी टिप्स",
    settings: "सेटिंग्ज",
    camera: "फोटो घ्या",
    gallery: "गॅलरी",
    changeLang: "भाषा बदला",
    updateProfile: "प्रोफाइल अपडेट करा"
  },
  bn: {
    welcome: "এগ্রিভিশনে স্বাগতম",
    selectLang: "ভাষা নির্বাচন করুন",
    loginTitle: "কৃষক লগইন",
    registerTitle: "কৃষক নিবন্ধন",
    phonePlaceholder: "মোবাইল নম্বর",
    namePlaceholder: "পুরো নাম",
    start: "শুরু করুন",
    sendOtp: "OTP পাঠান",
    verifyOtp: "যাচাই করুন এবং লগইন করুন",
    resend: "OTP পুনরায় পাঠান",
    otpPlaceholder: "4-সংখ্যার OTP লিখুন",
    switchLogin: "ইতিমধ্যে নিবন্ধিত? লগইন করুন",
    switchRegister: "নতুন ব্যবহারকারী? নিবন্ধন করুন",
    errorNameShort: "নাম অবশ্যই 6 অক্ষরের বেশি হতে হবে।",
    errorPhoneInvalid: "দয়া করে একটি বৈধ 10-সংখ্যার নম্বর লিখুন।",
    errorUserExists: "নম্বরটি ইতিমধ্যে নিবন্ধিত। অনুগ্রহ করে লগইন করুন।",
    errorUserNotFound: "নম্বর পাওয়া যায়নি। অনুগ্রহ করে প্রথমে নিবন্ধন করুন।",
    errorOtpInvalid: "অবৈধ OTP। অনুগ্রহ করে আবার চেষ্টা করুন।",
    otpSent: "OTP পাঠানো হয়েছে!",
    home: "হোম",
    detect: "রোগ শনাক্ত",
    profit: "লাভ ক্যালকুলেটর",
    history: "ইতিহাস",
    advisory: "পরামর্শ",
    uploadPhoto: "ছবি আপলোড করুন",
    analyzing: "ফসলের স্বাস্থ্য বিশ্লেষণ করা হচ্ছে...",
    results: "ফলাফল",
    treatment: "চিকিৎসা ও সমাধান",
    organic: "জৈব পদ্ধতি",
    chemical: "রাসায়নিক পদ্ধতি",
    prevention: "প্রতিরোধ",
    severity: "তীব্রতা",
    confidence: "AI বিশ্বাসযোগ্যতা",
    save: "সংরক্ষণ করুন",
    calculate: "লাভ গণনা করুন",
    investment: "মোট বিনিয়োগ",
    revenue: "প্রত্যাশিত আয়",
    netProfit: "নিট লাভ",
    profitPerAcre: "লাভ / একর",
    inputs: "কৃষি খরচ",
    calculating: "গণনা করা হচ্ছে...",
    weatherTips: "আবহাওয়া এবং টিপস",
    noHistory: "কোন পূর্ববর্তী স্ক্যান পাওয়া যায়নি।",
    weather: "আবহাওয়া রিপোর্ট",
    temperature: "তাপমাত্রা",
    humidity: "আর্দ্রতা",
    wind: "বাতাস",
    clear: "পরিষ্কার আকাশ",
    cloudy: "মেঘলা",
    rain: "বৃষ্টি",
    fog: "কুয়াশা",
    storm: "বজ্রঝড়",
    drizzle: "গুঁড়ি গুঁড়ি বৃষ্টি",
    locating: "অবস্থান খোঁজা হচ্ছে...",
    unknownLoc: "অজানা অবস্থান",
    healthyTitle: "সুখবর! আপনার গাছটি সুস্থ আছে।",
    careTips: "যত্নের টিপস",
    settings: "সেটিংস",
    camera: "ছবি তুলুন",
    gallery: "গ্যালারি",
    changeLang: "ভাষা পরিবর্তন করুন",
    updateProfile: "প্রোফাইল আপডেট করুন"
  },
  gu: {
    welcome: "એગ્રીવિઝનમાં આપનું સ્વાગત છે",
    selectLang: "ભાષા પસંદ કરો",
    loginTitle: "ખેડૂત લોગિન",
    registerTitle: "ખેડૂત નોંધણી",
    phonePlaceholder: "મોબાઇલ નંબર",
    namePlaceholder: "પૂરું નામ",
    start: "શરૂ કરો",
    sendOtp: "OTP મોકલો",
    verifyOtp: "ચકાસો અને લોગિન કરો",
    resend: "OTP ફરીથી મોકલો",
    otpPlaceholder: "4-અંકનો OTP દાખલ કરો",
    switchLogin: "પહેલેથી જ નોંધાયેલ છો? લોગિન કરો",
    switchRegister: "નવો વપરાશકર્તા? નોંધણી કરો",
    errorNameShort: "નામ 6 અક્ષરોથી વધુ હોવું જોઈએ.",
    errorPhoneInvalid: "કૃપા કરીને માન્ય 10-અંકનો નંબર દાખલ કરો.",
    errorUserExists: "નંબર પહેલેથી જ નોંધાયેલ છે. કૃપા કરીને લોગિન કરો.",
    errorUserNotFound: "નંબર મળ્યો નથી. કૃપા કરીને પહેલા નોંધણી કરો.",
    errorOtpInvalid: "અમાન્ય OTP. કૃપા કરીને ફરીથી પ્રયાસ કરો.",
    otpSent: "OTP મોકલ્યો!",
    home: "હોમ",
    detect: "રોગ ઓળખો",
    profit: "નફા કેલ્ક્યુલેટર",
    history: "ઇતિહાસ",
    advisory: "સલાહ",
    uploadPhoto: "ફોટો અપલોડ કરો",
    analyzing: "પાક આરોગ્ય વિશ્લેષણ...",
    results: "વિશ્લેષણ પરિણામો",
    treatment: "સારવાર અને ઉકેલો",
    organic: "જૈવિક પદ્ધતિ",
    chemical: "રાસાયણિક પદ્ધતિ",
    prevention: "નિવારણ",
    severity: "તીવ્રતા",
    confidence: "AI વિશ્વાસ",
    save: "સાચવો",
    calculate: "નફો ગણો",
    investment: "કુલ રોકાણ",
    revenue: "અપેક્ષિત આવક",
    netProfit: "ચોખ્ખો નફો",
    profitPerAcre: "નફો / એકર",
    inputs: "ખેતી ખર્ચ",
    calculating: "ગણતરી થઈ રહી છે...",
    weatherTips: "હવામાન અને ટીપ્સ",
    noHistory: "કોઈ જૂના સ્કેન મળ્યા નથી.",
    weather: "હવામાન અહેવાલ",
    temperature: "તાપમાન",
    humidity: "ભેજ",
    wind: "પવન",
    clear: "સ્વચ્છ આકાશ",
    cloudy: "વાદળછાયું",
    rain: "વરસાદ",
    fog: "ધુમ્મસ",
    storm: "વાવાઝોડું",
    drizzle: "ઝરમર વરસાદ",
    locating: "સ્થાન શોધી રહ્યું છે...",
    unknownLoc: "અજ્ઞાત સ્થાન",
    healthyTitle: "સારા સમાચાર! તમારો છોડ તંદુરસ્ત છે.",
    careTips: "સંભાળ ટીપ્સ",
    settings: "સેટિંગ્સ",
    camera: "ફોટો લો",
    gallery: "ગેલેરી",
    changeLang: "ભાષા બદલો",
    updateProfile: "પ્રોફાઇલ અપડેટ કરો"
  },
  pa: {
    welcome: "ਐਗਰੀਵਿਜ਼ਨ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
    selectLang: "ਭਾਸ਼ਾ ਚੁਣੋ",
    loginTitle: "ਕਿਸਾਨ ਲੌਗਇਨ",
    registerTitle: "ਕਿਸਾਨ ਰਜਿਸਟਰੇਸ਼ਨ",
    phonePlaceholder: "ਮੋਬਾਈਲ ਨੰਬਰ",
    namePlaceholder: "ਪੂਰਾ ਨਾਮ",
    start: "ਸ਼ੁਰੂ ਕਰੋ",
    sendOtp: "OTP ਭੇਜੋ",
    verifyOtp: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ",
    resend: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
    otpPlaceholder: "4-ਅੰਕ ਵਾਲਾ OTP ਭਰੋ",
    switchLogin: "ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰਡ? ਲੌਗਇਨ ਕਰੋ",
    switchRegister: "ਨਵਾਂ ਉਪਭੋਗਤਾ? ਰਜਿਸਟਰ ਕਰੋ",
    errorNameShort: "ਨਾਮ 6 ਅੱਖਰਾਂ ਤੋਂ ਵੱਧ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    errorPhoneInvalid: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਸਹੀ 10-ਅੰਕ ਵਾਲਾ ਨੰਬਰ ਭਰੋ।",
    errorUserExists: "ਨੰਬਰ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਲੌਗਇਨ ਕਰੋ।",
    errorUserNotFound: "ਨੰਬਰ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਰਜਿਸਟਰ ਕਰੋ।",
    errorOtpInvalid: "ਗਲਤ OTP। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    otpSent: "OTP ਭੇਜਿਆ ਗਿਆ!",
    home: "ਹੋਮ",
    detect: "ਰੋਗ ਪਛਾਣੋ",
    profit: "ਮੁਨਾਫਾ ਕੈਲਕੁਲੇਟਰ",
    history: "ਇਤਿਹਾਸ",
    advisory: "ਸਲਾਹ",
    uploadPhoto: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    analyzing: "ਫਸਲ ਦੀ ਸਿਹਤ ਦੀ ਜਾਂਚ...",
    results: "ਨਤੀਜੇ",
    treatment: "ਇਲਾਜ ਅਤੇ ਹੱਲ",
    organic: "ਜੈਵਿਕ ਤਰੀਕਾ",
    chemical: "ਰਸਾਇਣਕ ਤਰੀਕਾ",
    prevention: "ਰੋਕਥਾਮ",
    severity: "ਗੰਭੀਰਤਾ",
    confidence: "AI ਵਿਸ਼ਵਾਸ",
    save: "ਸੇਵ ਕਰੋ",
    calculate: "ਮੁਨਾਫਾ ਗਿਣੋ",
    investment: "ਕੁੱਲ ਨਿਵੇਸ਼",
    revenue: "ਉਮੀਦ ਕੀਤੀ ਆਮਦਨ",
    netProfit: "ਸ਼ੁੱਧ ਮੁਨਾਫਾ",
    profitPerAcre: "ਮੁਨਾਫਾ / ਏਕੜ",
    inputs: "ਖੇਤੀ ਖਰਚੇ",
    calculating: "ਗਿਣਤੀ ਹੋ ਰਹੀ ਹੈ...",
    weatherTips: "ਮੌਸਮ ਅਤੇ ਸੁਝਾਅ",
    noHistory: "ਕੋਈ ਪਿਛਲਾ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
    weather: "ਮੌਸਮ ਰਿਪੋਰਟ",
    temperature: "ਤਾਪਮਾਨ",
    humidity: "ਨਮੀ",
    wind: "ਹਵਾ",
    clear: "ਸਾਫ਼ ਅਸਮਾਨ",
    cloudy: "ਬੱਦਲਵਾਈ",
    rain: "ਮੀਂਹ",
    fog: "ਧੁੰਦ",
    storm: "ਤੂਫਾਨ",
    drizzle: "ਬੂੰਦਾ ਬਾਂਦੀ",
    locating: "ਸਥਾਨ ਲੱਭ ਰਿਹਾ ਹੈ...",
    unknownLoc: "ਅਣਜਾਣ ਸਥਾਨ",
    healthyTitle: "ਖੁਸ਼ਖਬਰੀ! ਤੁਹਾਡਾ ਪੌਦਾ ਸਿਹਤਮੰਦ ਹੈ।",
    careTips: "ਦੇਖਭਾਲ ਦੇ ਸੁਝਾਅ",
    settings: "ਸੈਟਿੰਗਜ਼",
    camera: "ਫੋਟੋ ਖਿੱਚੋ",
    gallery: "ਗੈਲਰੀ",
    changeLang: "ਭਾਸ਼ਾ ਬਦਲੋ",
    updateProfile: "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ"
  }
};
